package com.pbl.elearning.course.domain.enums;

public enum Category {
    PROGRAMMING,
    DESIGN,
    PROJECT_MANAGEMENT,
    DATA_SCIENCE,
    LANGUAGE_LEARNING,
    DEVELOPMENT,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    AI_AND_MACHINE_LEARNING,
    CYBERSECURITY,
    CLOUD_COMPUTING,
    DEVOPS,
    GAME_DEVELOPMENT,
    SOFTWARE_ENGINEERING,
    DATABASES
}
