server:
  port: 8105
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 60000
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
org:
  jobrunr:
    background-job-server:
      enabled: false
    dashboard:
      enabled: false
origin-patterns: "*"
dev-patterns: "http://localhost:3000"
web-url: "http://localhost:3000"
e-learning-mail:
  domain: e-learning.com
app:
  oauth2:
    providers:
      google:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}
        redirectUri: http://localhost:3000/oauth2/callback/google
      facebook:
        clientId: ${FACEBOOK_CLIENT_ID}
        clientSecret: ${FACEBOOK_CLIENT_SECRET}
        redirectUri: http://localhost:8105/api/v1/oauth2/facebook/login
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: us-east-1
  s3:
    bucket: e-learning-data